development:
  adapter: postgresql
  encoding: unicode
  database: items_development
  pool: 5
  username: Andrew
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: items_test
  pool: 5
  username: Andrew
  password: