# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 402fdd60a218695c5633b490acd01b4eeb03f56593ad103cccd29e4de7c7fba4c67be07e6f6ecd5baa6936d0b6373d315afc0f289be6b9d2cafe624ba0c2d4bc

test:
  secret_key_base: 89900cc30de0bdf2ef6c3f3428015c85be31156ee885239e8a973531a984e0b2226179a6aa69e401c7abcaacfbadcceeb1599f1161fa4782f79bc87f6fb68b12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: UA-36788567-5
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>